version: '3.8'
services:
  auth-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authUsers
    ports:
      - "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - marketplace-network
  catalog-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog
    ports:
      - "5433:5432"
    volumes:
      - catalog_data:/var/lib/postgresql/data
    networks:
      - marketplace-network
  order-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order
    ports:
      - "5434:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    networks:
      - marketplace-network

volumes:
  auth_data:
  catalog_data:
  order_data:

networks:
  marketplace-network:
    driver: bridge