spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/order
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
server:
  port: 8082